sonar.projectKey=rideHere
sonar.projectName=rideHere
sonar.sourceEncoding=UTF-8

# Código-fonte em TypeScript
sonar.sources=src
sonar.language=ts

# Diretório de testes (opcional, se quiser cobertura)
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusion=**/*.test.ts

# Diretório de saída do coverage (exemplo usando Jest)
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info
