name: CI of tests

on:
  pull_request:
    branches: [main, developer]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: checkout project
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: install dependencies
        run: npm install

      - name: docker start
        run: npm run docker:start

      - name: build project
        run: npm run build

      - name: run project
        run: npm run start &

      - name: run tests
        run: npm run test
